services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "${OLLAMA_HOST_PORT:-0}:11434"  # Dynamic host port, static container port
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0  # Listen on all interfaces inside container
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local
